// These are generated by AppTheme.

/**
 * All of our theme colors as the string that we use for the CSS property.
 */
export type ThemeColor =
	| 'darkest'
	| 'darker'
	| 'dark'
	| 'gray'
	| 'gray-subtle'
	| 'light'
	| 'lighter'
	| 'lightest'
	| 'highlight'
	| 'highlight-fg'
	| 'backlight'
	| 'backlight-fg'
	| 'notice'
	| 'notice-fg'
	| 'bi-bg'
	| 'bi-fg'
	| 'bg'
	| 'bg-offset'
	| 'bg-backdrop'
	| 'bg-subtle'
	| 'fg'
	| 'fg-muted'
	| 'link'
	| 'link-hover'
	| 'primary'
	| 'primary-fg';

// GJ Color Palette
export const kThemeGjGreen = `#cf0`;
export const kThemeGjDarkGreen = `#2f7f6f`;
export const kThemeGjPink = `#ff3fac`;
export const kThemeGjBlue = `#31d6ff`;
export const kThemeGjOverlayNotice = `#f11a5c`;

export const kThemeDarkest = `var(--theme-darkest)`;
export const kThemeDarker = `var(--theme-darker)`;
export const kThemeDark = `var(--theme-dark)`;
export const kThemeGray = `var(--theme-gray)`;
export const kThemeGraySubtle = `var(--theme-gray-subtle)`;
export const kThemeLight = `var(--theme-light)`;
export const kThemeLighter = `var(--theme-lighter)`;
export const kThemeLightest = `var(--theme-lightest)`;

export const kThemeHighlight = `var(--theme-highlight)`;
export const kThemeHighlightFg = `var(--theme-highlight-fg)`;
export const kThemeBacklight = `var(--theme-backlight)`;
export const kThemeBacklightFg = `var(--theme-backlight-fg)`;
export const kThemeNotice = `var(--theme-notice)`;
export const kThemeNoticeFg = `var(--theme-notice-fg)`;
export const kThemeBiBg = `var(--theme-bi-bg)`;
export const kThemeBiFg = `var(--theme-bi-fg)`;
export const kThemeBg = `var(--theme-bg)`;
export const kThemeBgActual = `var(--theme-bg-actual)`;
export const kThemeBgOffset = `var(--theme-bg-offset)`;
export const kThemeBgBackdrop = `var(--theme-bg-backdrop)`;
export const kThemeBgSubtle = `var(--theme-bg-subtle)`;
export const kThemeFg = `var(--theme-fg)`;
export const kThemeFgRgb = `var(--theme-fg-rgb)`;
export const kThemeFg10 = `rgba(${kThemeFgRgb}, 0.1)`;
export const kThemeFgMuted = `var(--theme-fg-muted)`;
export const kThemeLink = `var(--theme-link)`;
export const kThemeLinkHover = `var(--theme-link-hover)`;
export const kThemePrimary = `var(--theme-primary)`;
export const kThemePrimaryTrans = `var(--theme-primary-trans)`;
export const kThemePrimaryFg = `var(--theme-primary-fg)`;

export const kDarkThemeHighlight = `var(--dark-theme-highlight)`;
export const kDarkThemeBacklight = `var(--dark-theme-backlight)`;
export const kDarkThemeNotice = `var(--dark-theme-notice)`;
export const kDarkThemeBiBg = `var(--dark-theme-bi-bg)`;
export const kDarkThemeBiFg = `var(--dark-theme-bi-fg)`;
export const kDarkThemeBg = `var(--dark-theme-bg)`;
export const kDarkThemeBgOffset = `var(--dark-theme-bg-offset)`;
export const kDarkThemeBgBackdrop = `var(--dark-theme-bg-backdrop)`;
export const kDarkThemeBgSubtle = `var(--dark-theme-bg-subtle)`;
export const kDarkThemeFg = `var(--dark-theme-fg)`;
export const kDarkThemeFg10 = `rgba(var(--dark-theme-fg-rgb), 0.1)`;
export const kDarkThemeFgMuted = `var(--dark-theme-fg-muted)`;
export const kDarkThemeLink = `var(--dark-theme-link)`;
export const kDarkThemeLinkHover = `var(--dark-theme-link-hover)`;
export const kDarkThemePrimary = `var(--dark-theme-primary)`;
export const kDarkThemePrimaryFg = `var(--dark-theme-primary-fg)`;

// Context colors
export const kThemePlaceholderBg = kThemeBgSubtle;
