angular.module( 'App.Client', [
	'App.Client.Control',
	'App.Client.Shortcut',
	'App.Client.Autostart',
	'App.Client.Intro',
	'App.Client.User',
	'App.Client.LocalDb',
	'App.Client.Tray',
	'App.Client.MacAppMenu',
	'App.Client.Forms',
	'App.Client.Hidpi',
	'App.Client.Library',
	'App.Client.Installer',
	'App.Client.Launcher',
	'App.Client.HideOffline',
	'App.Client.ExternalLink',
	'App.Client.StatusBar',
	'App.Client.InstallProgress',
	'App.Client.GameButtons',
	'App.Client.InstallPackageModal',
	'App.Client.PackageCardOptions',
] );
