import { $gettext } from '../translate/translate.service';

export interface GeoCountry {
	code: string;
	name: string;
}

export interface GeoRegion {
	code: string;
	name: string;
}

class GeoService {
	private countries: GeoCountry[] = [];
	private regions: { [k: string]: GeoRegion[] } = {};

	getCountryName(code: string) {
		const country = this.getCountries().find(c => c.code === (code || '').toLowerCase());
		return country ? country.name : undefined;
	}

	getRegionName(country: string, code: string) {
		const regions = this.getRegions(country);
		if (!regions) {
			console.log('no region');
			return undefined;
		}

		const region = regions.find(c => c.code === (code || '').toLowerCase());
		return region ? region.name : undefined;
	}

	getCountries() {
		if (!this.countries.length) {
			this.countries = [
				{ code: 'af', name: $gettext('Afghanistan') },
				{ code: 'ax', name: $gettext('Aland Islands') },
				{ code: 'al', name: $gettext('Albania') },
				{ code: 'dz', name: $gettext('Algeria') },
				{ code: 'as', name: $gettext('American Samoa') },
				{ code: 'ad', name: $gettext('Andorra') },
				{ code: 'ao', name: $gettext('Angola') },
				{ code: 'ai', name: $gettext('Anguilla') },
				{ code: 'aq', name: $gettext('Antartica') },
				{ code: 'ag', name: $gettext('Antigua and Barbuda') },
				{ code: 'ar', name: $gettext('Argentina') },
				{ code: 'am', name: $gettext('Armenia') },
				{ code: 'aw', name: $gettext('Aruba') },
				{ code: 'au', name: $gettext('Australia') },
				{ code: 'at', name: $gettext('Austria') },
				{ code: 'az', name: $gettext('Azerbaijan') },
				{ code: 'bs', name: $gettext('Bahamas') },
				{ code: 'bh', name: $gettext('Bahrain') },
				{ code: 'bd', name: $gettext('Bangladesh') },
				{ code: 'bb', name: $gettext('Barbados') },
				{ code: 'by', name: $gettext('Belarus') },
				{ code: 'be', name: $gettext('Belgium') },
				{ code: 'bz', name: $gettext('Belize') },
				{ code: 'bj', name: $gettext('Benin') },
				{ code: 'bm', name: $gettext('Bermuda') },
				{ code: 'bt', name: $gettext('Bhutan') },
				{ code: 'bo', name: $gettext('Bolivia') },
				{
					code: 'bq',
					name: $gettext('Bonaire, Saint Eustatius and Saba'),
				},
				{ code: 'ba', name: $gettext('Bosnia and Herzegovina') },
				{ code: 'bw', name: $gettext('Botswana') },
				{ code: 'bv', name: $gettext('Bouvet Island') },
				{ code: 'br', name: $gettext('Brazil') },
				{
					code: 'io',
					name: $gettext('British Indian Ocean Territory'),
				},
				{ code: 'vg', name: $gettext('British Virgin Islands') },
				{ code: 'bn', name: $gettext('Brunei') },
				{ code: 'bg', name: $gettext('Bulgaria') },
				{ code: 'bf', name: $gettext('Burkina Faso') },
				{ code: 'bi', name: $gettext('Burundi') },
				{ code: 'kh', name: $gettext('Cambodia') },
				{ code: 'cm', name: $gettext('Cameroon') },
				{ code: 'ca', name: $gettext('Canada') },
				{ code: 'cv', name: $gettext('Cape Verde') },
				{ code: 'ky', name: $gettext('Cayman Islands') },
				{ code: 'cf', name: $gettext('Central African Republic') },
				{ code: 'td', name: $gettext('Chad') },
				{ code: 'cl', name: $gettext('Chile') },
				{ code: 'cn', name: $gettext('China') },
				{ code: 'cx', name: $gettext('Christmas Island') },
				{ code: 'cc', name: $gettext('Cocos Islands') },
				{ code: 'co', name: $gettext('Colombia') },
				{ code: 'km', name: $gettext('Comoros') },
				{ code: 'ck', name: $gettext('Cook Islands') },
				{ code: 'cr', name: $gettext('Costa Rica') },
				{ code: 'hr', name: $gettext('Croatia') },
				{ code: 'cu', name: $gettext('Cuba') },
				{ code: 'cw', name: $gettext('Curacao') },
				{ code: 'cy', name: $gettext('Cyprus') },
				{ code: 'cz', name: $gettext('Czech Republic') },
				{
					code: 'cd',
					name: $gettext('Democratic Republic of the Congo'),
				},
				{ code: 'dk', name: $gettext('Denmark') },
				{ code: 'dj', name: $gettext('Djibouti') },
				{ code: 'dm', name: $gettext('Dominica') },
				{ code: 'do', name: $gettext('Dominican Republic') },
				{ code: 'tl', name: $gettext('East Timor') },
				{ code: 'ec', name: $gettext('Ecuador') },
				{ code: 'eg', name: $gettext('Egypt') },
				{ code: 'sv', name: $gettext('El Salvador') },
				{ code: 'gq', name: $gettext('Equatorial Guinea') },
				{ code: 'er', name: $gettext('Eritrea') },
				{ code: 'ee', name: $gettext('Estonia') },
				{ code: 'et', name: $gettext('Ethiopia') },
				{ code: 'fk', name: $gettext('Falkland Islands') },
				{ code: 'fo', name: $gettext('Faroe Islands') },
				{ code: 'fj', name: $gettext('Fiji') },
				{ code: 'fi', name: $gettext('Finland') },
				{ code: 'fr', name: $gettext('France') },
				{ code: 'gf', name: $gettext('French Guiana') },
				{ code: 'pf', name: $gettext('French Polynesia') },
				{ code: 'tf', name: $gettext('French Southern Territories') },
				{ code: 'ga', name: $gettext('Gabon') },
				{ code: 'gm', name: $gettext('Gambia') },
				{ code: 'ge', name: $gettext('Georgia') },
				{ code: 'de', name: $gettext('Germany') },
				{ code: 'gh', name: $gettext('Ghana') },
				{ code: 'gi', name: $gettext('Gibraltar') },
				{ code: 'gr', name: $gettext('Greece') },
				{ code: 'gl', name: $gettext('Greenland') },
				{ code: 'gd', name: $gettext('Grenada') },
				{ code: 'gp', name: $gettext('Guadeloupe') },
				{ code: 'gu', name: $gettext('Guam') },
				{ code: 'gt', name: $gettext('Guatemala') },
				{ code: 'gg', name: $gettext('Guernsey') },
				{ code: 'gn', name: $gettext('Guinea') },
				{ code: 'gw', name: $gettext('Guinea-Bissau') },
				{ code: 'gy', name: $gettext('Guyana') },
				{ code: 'ht', name: $gettext('Haiti') },
				{
					code: 'hm',
					name: $gettext('Heard Island and McDonald Islands'),
				},
				{ code: 'hn', name: $gettext('Honduras') },
				{ code: 'hk', name: $gettext('Hong Kong') },
				{ code: 'hu', name: $gettext('Hungary') },
				{ code: 'is', name: $gettext('Iceland') },
				{ code: 'in', name: $gettext('India') },
				{ code: 'id', name: $gettext('Indonesia') },
				{ code: 'ir', name: $gettext('Iran') },
				{ code: 'iq', name: $gettext('Iraq') },
				{ code: 'ie', name: $gettext('Ireland') },
				{ code: 'im', name: $gettext('Isle of Man') },
				{ code: 'il', name: $gettext('Israel') },
				{ code: 'it', name: $gettext('Italy') },
				{ code: 'ci', name: $gettext('Ivory Coast') },
				{ code: 'jm', name: $gettext('Jamaica') },
				{ code: 'jp', name: $gettext('Japan') },
				{ code: 'je', name: $gettext('Jersey') },
				{ code: 'jo', name: $gettext('Jordan') },
				{ code: 'kz', name: $gettext('Kazakhstan') },
				{ code: 'ke', name: $gettext('Kenya') },
				{ code: 'ki', name: $gettext('Kiribati') },
				{ code: 'xk', name: $gettext('Kosovo') },
				{ code: 'kw', name: $gettext('Kuwait') },
				{ code: 'kg', name: $gettext('Kyrgyzstan') },
				{ code: 'la', name: $gettext('Laos') },
				{ code: 'lv', name: $gettext('Latvia') },
				{ code: 'lb', name: $gettext('Lebanon') },
				{ code: 'ls', name: $gettext('Lesotho') },
				{ code: 'lr', name: $gettext('Liberia') },
				{ code: 'ly', name: $gettext('Libya') },
				{ code: 'li', name: $gettext('Liechtenstein') },
				{ code: 'lt', name: $gettext('Lithuania') },
				{ code: 'lu', name: $gettext('Luxembourg') },
				{ code: 'mo', name: $gettext('Macao') },
				{ code: 'mk', name: $gettext('Macedonia') },
				{ code: 'mg', name: $gettext('Madagascar') },
				{ code: 'mw', name: $gettext('Malawi') },
				{ code: 'my', name: $gettext('Malaysia') },
				{ code: 'mv', name: $gettext('Maldives') },
				{ code: 'ml', name: $gettext('Mali') },
				{ code: 'mt', name: $gettext('Malta') },
				{ code: 'mh', name: $gettext('Marshall Islands') },
				{ code: 'mq', name: $gettext('Martinique') },
				{ code: 'mr', name: $gettext('Mauritania') },
				{ code: 'mu', name: $gettext('Mauritius') },
				{ code: 'yt', name: $gettext('Mayotte') },
				{ code: 'mx', name: $gettext('Mexico') },
				{ code: 'fm', name: $gettext('Micronesia') },
				{ code: 'md', name: $gettext('Moldova') },
				{ code: 'mc', name: $gettext('Monaco') },
				{ code: 'mn', name: $gettext('Mongolia') },
				{ code: 'me', name: $gettext('Montenegro') },
				{ code: 'ms', name: $gettext('Montserrat') },
				{ code: 'ma', name: $gettext('Morocco') },
				{ code: 'mz', name: $gettext('Mozambique') },
				{ code: 'mm', name: $gettext('Myanmar') },
				{ code: 'na', name: $gettext('Namibia') },
				{ code: 'nr', name: $gettext('Nauru') },
				{ code: 'np', name: $gettext('Nepal') },
				{ code: 'nl', name: $gettext('Netherlands') },
				{ code: 'nc', name: $gettext('New Caledonia') },
				{ code: 'nz', name: $gettext('New Zealand') },
				{ code: 'ni', name: $gettext('Nicaragua') },
				{ code: 'ne', name: $gettext('Niger') },
				{ code: 'ng', name: $gettext('Nigeria') },
				{ code: 'nu', name: $gettext('Niue') },
				{ code: 'nf', name: $gettext('Norfolk Island') },
				{ code: 'kp', name: $gettext('North Korea') },
				{ code: 'mp', name: $gettext('Northern Mariana Islands') },
				{ code: 'no', name: $gettext('Norway') },
				{ code: 'om', name: $gettext('Oman') },
				{ code: 'pk', name: $gettext('Pakistan') },
				{ code: 'pw', name: $gettext('Palau') },
				{ code: 'ps', name: $gettext('Palestinian Territory') },
				{ code: 'pa', name: $gettext('Panama') },
				{ code: 'pg', name: $gettext('Papua New Guinea') },
				{ code: 'py', name: $gettext('Paraguay') },
				{ code: 'pe', name: $gettext('Peru') },
				{ code: 'ph', name: $gettext('Philippines') },
				{ code: 'pn', name: $gettext('Pitcairn') },
				{ code: 'pl', name: $gettext('Poland') },
				{ code: 'pt', name: $gettext('Portugal') },
				{ code: 'pr', name: $gettext('Puerto Rico') },
				{ code: 'qa', name: $gettext('Qatar') },
				{ code: 'cg', name: $gettext('Republic of the Congo') },
				{ code: 're', name: $gettext('Reunion') },
				{ code: 'ro', name: $gettext('Romania') },
				{ code: 'ru', name: $gettext('Russia') },
				{ code: 'rw', name: $gettext('Rwanda') },
				{ code: 'bl', name: $gettext('Saint Barthelemy') },
				{ code: 'sh', name: $gettext('Saint Helena') },
				{ code: 'kn', name: $gettext('Saint Kitts and Nevis') },
				{ code: 'lc', name: $gettext('Saint Lucia') },
				{ code: 'mf', name: $gettext('Saint Martin') },
				{ code: 'pm', name: $gettext('Saint Pierre and Miquelon') },
				{
					code: 'vc',
					name: $gettext('Saint Vincent and the Grenadines'),
				},
				{ code: 'ws', name: $gettext('Samoa') },
				{ code: 'sm', name: $gettext('San Marino') },
				{ code: 'st', name: $gettext('Sao Tome and Principe') },
				{ code: 'sa', name: $gettext('Saudi Arabia') },
				{ code: 'sn', name: $gettext('Senegal') },
				{ code: 'rs', name: $gettext('Serbia') },
				{ code: 'sc', name: $gettext('Seychelles') },
				{ code: 'sl', name: $gettext('Sierra Leone') },
				{ code: 'sg', name: $gettext('Singapore') },
				{ code: 'sx', name: $gettext('Sint Maarten') },
				{ code: 'sk', name: $gettext('Slovakia') },
				{ code: 'si', name: $gettext('Slovenia') },
				{ code: 'sb', name: $gettext('Solomon Islands') },
				{ code: 'so', name: $gettext('Somalia') },
				{ code: 'za', name: $gettext('South Africa') },
				{
					code: 'gs',
					name: $gettext('South Georgia and the South Sandwich Islands'),
				},
				{ code: 'kr', name: $gettext('South Korea') },
				{ code: 'ss', name: $gettext('South Sudan') },
				{ code: 'es', name: $gettext('Spain') },
				{ code: 'lk', name: $gettext('Sri Lanka') },
				{ code: 'sd', name: $gettext('Sudan') },
				{ code: 'sr', name: $gettext('Suriname') },
				{ code: 'sj', name: $gettext('Svalbard and Jan Mayen') },
				{ code: 'sz', name: $gettext('Swaziland') },
				{ code: 'se', name: $gettext('Sweden') },
				{ code: 'ch', name: $gettext('Switzerland') },
				{ code: 'sy', name: $gettext('Syria') },
				{ code: 'tw', name: $gettext('Taiwan') },
				{ code: 'tj', name: $gettext('Tajikistan') },
				{ code: 'tz', name: $gettext('Tanzania') },
				{ code: 'th', name: $gettext('Thailand') },
				{ code: 'tg', name: $gettext('Togo') },
				{ code: 'tk', name: $gettext('Tokelau') },
				{ code: 'to', name: $gettext('Tonga') },
				{ code: 'tt', name: $gettext('Trinidad and Tobago') },
				{ code: 'tn', name: $gettext('Tunisia') },
				{ code: 'tr', name: $gettext('Turkey') },
				{ code: 'tm', name: $gettext('Turkmenistan') },
				{ code: 'tc', name: $gettext('Turks and Caicos Islands') },
				{ code: 'tv', name: $gettext('Tuvalu') },
				{ code: 'vi', name: $gettext('U.S. Virgin Islands') },
				{ code: 'ug', name: $gettext('Uganda') },
				{ code: 'ua', name: $gettext('Ukraine') },
				{ code: 'ae', name: $gettext('United Arab Emirates') },
				{ code: 'gb', name: $gettext('United Kingdom') },
				{ code: 'us', name: $gettext('United States') },
				{
					code: 'um',
					name: $gettext('United States Minor Outlying Islands'),
				},
				{ code: 'uy', name: $gettext('Uruguay') },
				{ code: 'uz', name: $gettext('Uzbekistan') },
				{ code: 'vu', name: $gettext('Vanuatu') },
				{ code: 'va', name: $gettext('Vatican') },
				{ code: 've', name: $gettext('Venezuela') },
				{ code: 'vn', name: $gettext('Vietnam') },
				{ code: 'wf', name: $gettext('Wallis and Futuna') },
				{ code: 'eh', name: $gettext('Western Sahara') },
				{ code: 'ye', name: $gettext('Yemen') },
				{ code: 'zm', name: $gettext('Zambia') },
				{ code: 'zw', name: $gettext('Zimbabwe') },
			];
		}

		return this.countries;
	}

	getRegions(country: string): GeoRegion[] | undefined {
		if (!this.regions[country]) {
			if (country === 'us') {
				this.regions[country] = [
					{ code: 'al', name: $gettext('Alabama') },
					{ code: 'ak', name: $gettext('Alaska') },
					{ code: 'az', name: $gettext('Arizona') },
					{ code: 'ar', name: $gettext('Arkansas') },
					{ code: 'ca', name: $gettext('California') },
					{ code: 'co', name: $gettext('Colorado') },
					{ code: 'ct', name: $gettext('Connecticut') },
					{ code: 'de', name: $gettext('Delaware') },
					{ code: 'fl', name: $gettext('Florida') },
					{ code: 'ga', name: $gettext('Georgia') },
					{ code: 'hi', name: $gettext('Hawaii') },
					{ code: 'id', name: $gettext('Idaho') },
					{ code: 'il', name: $gettext('Illinois') },
					{ code: 'in', name: $gettext('Indiana') },
					{ code: 'ia', name: $gettext('Iowa') },
					{ code: 'ks', name: $gettext('Kansas') },
					{ code: 'ky', name: $gettext('Kentucky') },
					{ code: 'la', name: $gettext('Louisiana') },
					{ code: 'me', name: $gettext('Maine') },
					{ code: 'md', name: $gettext('Maryland') },
					{ code: 'ma', name: $gettext('Massachusetts') },
					{ code: 'mi', name: $gettext('Michigan') },
					{ code: 'mn', name: $gettext('Minnesota') },
					{ code: 'ms', name: $gettext('Mississippi') },
					{ code: 'mo', name: $gettext('Missouri') },
					{ code: 'mt', name: $gettext('Montana') },
					{ code: 'ne', name: $gettext('Nebraska') },
					{ code: 'nv', name: $gettext('Nevada') },
					{ code: 'nh', name: $gettext('New Hampshire') },
					{ code: 'nj', name: $gettext('New Jersey') },
					{ code: 'nm', name: $gettext('New Mexico') },
					{ code: 'ny', name: $gettext('New York') },
					{ code: 'nc', name: $gettext('North Carolina') },
					{ code: 'nd', name: $gettext('North Dakota') },
					{ code: 'oh', name: $gettext('Ohio') },
					{ code: 'ok', name: $gettext('Oklahoma') },
					{ code: 'or', name: $gettext('Oregon') },
					{ code: 'pa', name: $gettext('Pennsylvania') },
					{ code: 'ri', name: $gettext('Rhode Island') },
					{ code: 'sc', name: $gettext('South Carolina') },
					{ code: 'sd', name: $gettext('South Dakota') },
					{ code: 'tn', name: $gettext('Tennessee') },
					{ code: 'tx', name: $gettext('Texas') },
					{ code: 'ut', name: $gettext('Utah') },
					{ code: 'vt', name: $gettext('Vermont') },
					{ code: 'va', name: $gettext('Virginia') },
					{ code: 'wa', name: $gettext('Washington') },
					{ code: 'wv', name: $gettext('West Virginia') },
					{ code: 'wi', name: $gettext('Wisconsin') },
					{ code: 'wy', name: $gettext('Wyoming') },
					{ code: 'dc', name: $gettext('Washington D.C.') },
					{ code: 'as', name: $gettext('American Samoa') },
					{ code: 'gu', name: $gettext('Guam') },
					{ code: 'mp', name: $gettext('Northern Mariana Islands') },
					{ code: 'pr', name: $gettext('Puerto Rico') },
					{ code: 'vi', name: $gettext('U.S. Virgin Islands') },
				];
			} else if (country === 'ca') {
				this.regions[country] = [
					{ code: 'on', name: 'Ontario' },
					{ code: 'qc', name: 'Quebec' },
					{ code: 'ns', name: 'Nova Scotia' },
					{ code: 'nb', name: 'New Brunswick' },
					{ code: 'mb', name: 'Manitoba' },
					{ code: 'bc', name: 'British Columbia' },
					{ code: 'pe', name: 'Prince Edward Island' },
					{ code: 'sk', name: 'Saskatchewan' },
					{ code: 'ab', name: 'Alberta' },
					{ code: 'nl', name: 'Newfoundland and Labrador' },
					{ code: 'nt', name: 'Northwest Territories' },
					{ code: 'yt', name: 'Yukon' },
					{ code: 'nu', name: 'Nunavut' },
				];
			}
		}

		return this.regions[country];
	}
}

export const Geo = /** @__PURE__ */ new GeoService();
