<script lang="ts" setup>
import { determine } from 'jstimezonedetect';
import { PropType, computed, nextTick, ref, toRef, toRefs } from 'vue';
import {
	$saveCommunityChannel,
	CommunityChannelModel,
} from '../../../../../../_common/community/channel/channel.model';
import { CommunityModel } from '../../../../../../_common/community/community.model';
import AppForm, {
	FormController,
	createForm,
} from '../../../../../../_common/form-vue/AppForm.vue';
import AppFormButton from '../../../../../../_common/form-vue/AppFormButton.vue';
import AppFormControl from '../../../../../../_common/form-vue/AppFormControl.vue';
import AppFormControlError from '../../../../../../_common/form-vue/AppFormControlError.vue';
import AppFormControlErrors from '../../../../../../_common/form-vue/AppFormControlErrors.vue';
import AppFormGroup from '../../../../../../_common/form-vue/AppFormGroup.vue';
import AppFormControlRadio from '../../../../../../_common/form-vue/controls/AppFormControlRadio.vue';
import {
	validateAvailability,
	validateMaxLength,
	validateMinLength,
	validatePattern,
} from '../../../../../../_common/form-vue/validators';
import { useCommonStore } from '../../../../../../_common/store/common-store';
import { $gettext } from '../../../../../../_common/translate/translate.service';
import AppFormCommunityChannelPermissions from '../_permissions/permissions.vue';

interface FormModel extends CommunityChannelModel {
	permission_posting?: string;
	timezone?: string;
}

const types = [
	{
		radioValue: 'post-feed',
		text: $gettext(`Posts`),
		helpText: $gettext(`Displays a feed of posts`),
	},
	{
		radioValue: 'competition',
		text: $gettext(`Game Jam`),
		helpText: $gettext(
			`A competition to create games within a certain timeframe, usually around a particular theme`
		),
	},
];

const props = defineProps({
	community: {
		type: Object as PropType<CommunityModel>,
		required: true,
	},
	channels: {
		type: Array as PropType<CommunityChannelModel[]>,
		required: true,
	},
	archivedChannels: {
		type: Array as PropType<CommunityChannelModel[]>,
		required: true,
	},
});

const { community, channels, archivedChannels } = toRefs(props);

const { user } = useCommonStore();

const isTitleInitial = ref(true);

// TODO: for now, only site mods are allowed to create jam channels.
const shouldShowType = toRef(() => user.value && user.value.permission_level >= 3);

const isValid = computed(() => {
	if (!form.valid) {
		return false;
	}

	return (
		!!form.formModel.title &&
		form.formModel.title.trim().length >= 3 &&
		form.formModel.title.trim().length <= 30 &&
		!isTitleTaken(form.formModel.title)
	);
});

const form: FormController<FormModel> = createForm({
	modelClass: CommunityChannelModel,
	modelSaveHandler: $saveCommunityChannel,
	resetOnSubmit: true,
	onInit() {
		form.formModel.community_id = community.value.id;
		form.formModel.type = 'post-feed';
		form.formModel.permission_posting = 'all';
		// Used to submit a default timezone for a competition when creating a competition channel.
		form.formModel.timezone = determine().name();
	},
});

function isTitleTaken(title: string) {
	return [...channels.value, ...archivedChannels.value]
		.map(i => i.title.toLowerCase().trim())
		.includes(title.toLowerCase().trim());
}

async function onChangedDisplayTitle() {
	if (!isTitleInitial.value) {
		return;
	}

	if (form.formModel.display_title) {
		// Autogenerate a valid title for the display title.
		let formTitle = form.formModel.display_title
			// Titles are always lower case, display titles aren't.
			.toLowerCase()
			.trim()
			// Replace any invalid title chars with "_".
			.replace(/[^a-z0-9_]/g, '_');

		// Try and remove underscores from start/end.
		// Example: display title of "> Channel <" ends up with "channel" instead of "__channel__".
		while (formTitle.startsWith('_')) {
			formTitle = formTitle.substring(1);
		}
		while (formTitle.endsWith('_')) {
			formTitle = formTitle.substring(0, formTitle.length - 1);
		}

		// Enforce max title length.
		formTitle = formTitle.substring(0, 30);

		let title = formTitle;

		if (formTitle !== '') {
			let num = 0;

			// When long as the autogenerated title is taken, append a number to the end like this:
			// <title>_<num>
			// Loop until this generates a title that is not taken, with num counting up.
			while (isTitleTaken(title)) {
				num++;
				const numStr = '_' + num.toString();
				// Make sure that the title and the _<num> suffix do not exceed title length requirements.
				formTitle = formTitle.substring(0, 30 - numStr.length);
				title = formTitle + numStr;
			}
		}

		form.formModel.title = title;

		// Validate the form manually once the title field is valid.
		if (title.length >= 3) {
			await nextTick();
			form.validate();
		}
	} else {
		form.formModel.title = '';

		await nextTick();
		form.validate();
	}
}

function onChangedTitle() {
	if (form.formModel.title === '') {
		isTitleInitial.value = true;
	} else {
		// When the user types a custom title, do not overwrite it when typing a display title.
		isTitleInitial.value = false;
	}
}
</script>

<template>
	<AppForm :controller="form">
		<AppFormGroup name="display_title" :label="$gettext(`Display Name`)" optional>
			<div class="help-block">
				{{
					$gettext(
						`This should be short and to the point. If you don't fill in a display name, we'll use your channel's URL path as its name.`
					)
				}}
			</div>

			<AppFormControl
				:validators="[validateMinLength(3), validateMaxLength(30)]"
				validate-on-blur
				:placeholder="form.formModel.title"
				@changed="onChangedDisplayTitle"
			/>

			<AppFormControlErrors />
		</AppFormGroup>

		<AppFormGroup name="title" :label="$gettext(`URL Path`)">
			<AppFormControl
				type="text"
				:validators="[
					validateMinLength(3),
					validateMaxLength(30),
					validatePattern(/^[a-z0-9_]+$/i),
					validateAvailability({
						url: `/web/dash/communities/channels/check-field-availability/${community.id}`,
					}),
				]"
				:validate-delay="500"
				validate-on-blur
				@changed="onChangedTitle"
			/>
			<AppFormControlErrors>
				<AppFormControlError
					when="too_many_channels"
					:message="
						$gettext(
							'This community already has the maximum number of channels allowed.'
						)
					"
				/>

				<AppFormControlError
					when="availability"
					:message="
						$gettext('A channel in this community with that URL path already exists.')
					"
				/>

				<AppFormControlError
					when="pattern"
					:message="
						$gettext(
							'Channel names can only contain numbers, letters, and underscores (_).'
						)
					"
				/>
			</AppFormControlErrors>
		</AppFormGroup>

		<AppFormCommunityChannelPermissions />

		<AppFormGroup v-if="shouldShowType" name="type" :label="$gettext(`Channel Type`)">
			<div v-for="channelType of types" :key="channelType.radioValue" class="radio">
				<label>
					<AppFormControlRadio :value="channelType.radioValue" />
					{{ channelType.text }}
					<span v-if="channelType.helpText" class="help-inline">
						- {{ channelType.helpText }}
					</span>
				</label>
			</div>
		</AppFormGroup>

		<AppFormButton :disabled="!isValid">
			{{ $gettext(`Add`) }}
		</AppFormButton>
	</AppForm>
</template>
